### ISSUE TITLE
Fahrenheit

### ISSUE THREAD

**Issue by franglais125** [franglais125/gnome-shell-system-monitor-applet#1]
@eimmot @jwhipp
Hi, I moved the discussion off the other thread not so spam everyone.
Can you test the patch I prepared to fix the Fahrenheit issue? I tested locally and it seems to be fixed for me.

Here is how to proceed:
1. Install:
```
git checkout https://github.com/franglais125/gnome-shell-system-monitor-applet
cd gnome-shell-system-monitor-applet
make && make install
```

2. Choose the "Display temperature in Fahrenheit" option.

3. Logout and login again.

**Comment by jwhipp** [comment]
Is there a particular branch or commit to be checked out?

**Comment by franglais125** [comment]
This is the commit: [f1d555686e95fa48d5795bb4749520a94db7cfc8], which is included in the master branch! :)

**Comment by jwhipp** [comment]
Worked.

One note for anyone else trying is to ALT-F2 and type 'r' to restart Gnome Shell.

![selection_001](https://cloud.githubusercontent.com/assets/556332/25541568/5cd9a990-2c0c-11e7-8182-6c3c395643a4.png)

**Comment by franglais125** [comment]
Awesome, thanks. I didn't mention the Alt-F2 thing, since it wouldn't work for Wayland, I just wanted to be 100% sure the extension was being fully reloaded. Thanks for testing! I'll open a PR for this.
